# -*- coding: utf-8 -*-
"""Text_Generation_With_GPT-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HdUZEluo4oO1NAVpLKl0mn1XvN_gQJY3
"""

!pip install transformers datasets torch accelerate

from datasets import load_dataset

dataset = load_dataset("text", data_files="custom_data.txt")
dataset = dataset["train"].train_test_split(test_size=0.1)  # 90/10 train/validation split

from datasets import load_dataset

dataset = load_dataset("text", data_files="custom_data.txt")
dataset = dataset["train"].train_test_split(test_size=0.1)  # 90/10 train/validation split

from transformers import GPT2Tokenizer, AutoTokenizer

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token  # Fix padding issue

def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=128, return_tensors="pt")

tokenized_datasets = dataset.map(tokenize_function, batched=True, remove_columns=dataset["train"].column_names)

from transformers import GPT2LMHeadModel, TrainingArguments, Trainer, DataCollatorForLanguageModeling
import torch

model = GPT2LMHeadModel.from_pretrained("gpt2")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

training_args = TrainingArguments(
    output_dir="./gpt2-finetuned",
    # overwrite_output_dir=True, # Removed to fix TypeError, consider restarting runtime if issues persist
    num_train_epochs=3,  # 3 epochs for small data; monitor loss
    per_device_train_batch_size=4,  # Adjust based on GPU (Colab T4: 4-8)
    per_device_eval_batch_size=4,
    warmup_steps=50,
    weight_decay=0.01,
    logging_steps=10,
    save_steps=100,
    # evaluation_strategy="steps", # Removed to fix TypeError, consider restarting runtime if issues persist
    # eval_steps=50, # Removed as it depends on evaluation_strategy
)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)  # Causal LM, not masked

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    data_collator=data_collator,
)

trainer.train()
trainer.save_model("./gpt2-finetuned")
tokenizer.save_pretrained("./gpt2-finetuned")

from transformers import pipeline

generator = pipeline("text-generation", model="./gpt2-finetuned", tokenizer=tokenizer, device=0 if torch.cuda.is_available() else -1)

prompt = "Once upon a time"
result = generator(prompt, max_length=100, num_return_sequences=1, temperature=0.7, do_sample=True, pad_token_id=tokenizer.eos_token_id)
print(result[0]["generated_text"])